# User-defined variables
n = 5  # Replace with any positive integer for the modulus
generator = 2  # Replace with the chosen generator element

# Function to compute the subgroup generated by the given element
def generate_subgroup(n, generator):
    subgroup = set()
    current = generator
    while current not in subgroup:
        subgroup.add(current)
        current = (current + generator) % n
    return subgroup

# Compute the subgroup
subgroup = generate_subgroup(n, generator)

# Print the result in the desired format
print(f"<{generator}> = {subgroup}")
